ALTER TABLE shuttle
    ADD COLUMN operating_days
        SET ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')
        DEFAULT 'MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY';
