management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - info
          - metrics
          - threaddump
  metrics:
    enable:
      hikaricp: true

spring:
  datasource:
    hikari:
      register-mbeans: true
